In [1]:
import numpy as np
import pandas as pd
import time
from datetime import date, timedelta
import datetime
# Import the API key.
from config import EIA_key
import eia
# Import the requests library.
import requests
#Display all columns
pd.set_option('display.max_columns', None)
import json

# API Call for State Production

In [2]:
# USA API
API_Call_USA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPUS1.M"
Series_Name_USA= "U.S. Field Production of Crude Oil, Monthly"
Series_ID_USA= "PET.MCRFPUS1.M"
# FL API
API_Call_FL=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPFL1.M"
Series_Name_FL= "Florida Field Production of Crude Oil, Monthly"
Series_ID_FL= "PET.MCRFPFL1.M"
#NY API
API_Call_NY=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPNY1.M"
Series_Name_NY= "New York Field Production of Crude Oil, Monthly"
Series_ID_NY= "PET.MCRFPNY1.M"
#PA API
API_Call_PA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPPA1.M"
Series_Name_PA= "Pennsylvania Field Production of Crude Oil, Monthly"
Series_ID_PA= "PET.MCRFPPA1.M"
#VA API
API_Call_VA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPVA1.M"
Series_Name_VA= "Virginia Field Production of Crude Oil, Monthly"
Series_ID_VA= "PET.MCRFPVA1.M"
#WV API
API_Call_WV=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPWV1.M"
Series_Name_WV= "West Virginia Field Production of Crude Oil, Monthly"
Series_ID_WV= "PET.MCRFPWV1.M"
#IL API
API_Call_IL=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPIL1.M"
Series_Name_IL= "Illinois Field Production of Crude Oil, Monthly"
Series_ID_IL= "PET.MCRFPIL1.M"
#IN API
API_Call_IN=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPIN1.M"
Series_Name_IN= "Indiana Field Production of Crude Oil, Monthly"
Series_ID_IN= "PET.MCRFPIN1.M"
#KS API
API_Call_KS=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPKS1.M"
Series_Name_KS= "Kansas Field Production of Crude Oil, Monthly"
Series_ID_KS= "PET.MCRFPKS1.M"
#KY API
API_Call_KY=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPKY1.M"
Series_Name_KY= "Kentucky Field Production of Crude Oil, Monthly"
Series_ID_KY= "PET.MCRFPKY1.M"
#MI API
API_Call_MI=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFP_SMI_1.M"
Series_Name_MI= "Michigan Field Production of Crude Oil, Monthly"
Series_ID_MI= "PET.MCRFP_SMI_1.M "
#MO API
API_Call_MO=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPMO1.M"
Series_Name_MO= "Missouri Field Production of Crude Oil, Monthly"
Series_ID_MO= "PET.MCRFPMO1.M"
#NE API
API_Call_NE=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPNE1.M"
Series_Name_NE= "Nebraska Field Production of Crude Oil, Monthly"
Series_ID_NE= "PET.MCRFPNE1.M"
#ND API
API_Call_ND=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPND1.M"
Series_Name_ND= "North Dakota Field Production of Crude Oil, Monthly"
Series_ID_ND= "PET.MCRFPND1.M"
#OH API
API_Call_OH=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPOH1.M"
Series_Name_OH= "Ohio Field Production of Crude Oil, Monthly"
Series_ID_OH= "PET.MCRFPOH1.M"
#OK API
API_Call_OK=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPOK1.M"
Series_Name_OK= "Oklahoma Field Production of Crude Oil, Monthly"
Series_ID_OK= "PET.MCRFPOK1.M"
#SD API
API_Call_SD=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPSD1.M"
Series_Name_SD= "South Dakota Field Production of Crude Oil, Monthly"
Series_ID_SD= "PET.MCRFPSD1.M"
#TN API
API_Call_TN=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPTN1.M"
Series_Name_TN= "Tennessee Field Production of Crude Oil, Monthly"
Series_ID_TN= "PET.MCRFPTN1.M"
#AL API
API_Call_AL=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPAL1.M"
Series_Name_AL= "Alabama Field Production of Crude Oil, Monthly"
Series_ID_AL= "PET.MCRFPAL1.M"
#AR API
API_Call_AR=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPAR1.M"
Series_Name_AR= "Arkansas Field Production of Crude Oil, Monthly"
Series_ID_AR= "PET.MCRFPAR1.M"
#LA API
API_Call_LA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPLA1.M"
Series_Name_LA= "Louisiana Field Production of Crude Oil, Monthly"
Series_ID_LA= "PET.MCRFPLA1.M"
#MS API
API_Call_MS=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPMS1.M"
Series_Name_MS= "Mississippi Field Production of Crude Oil, Monthly"
Series_ID_MS= "PET.MCRFPMS1.M"
#NM API
API_Call_NM=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPNM1.M"
Series_Name_NM= "New Mexico Field Production of Crude Oil, Monthly"
Series_ID_NM= "PET.MCRFPNM1.M"
#TX API
API_Call_TX=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPTX1.M"
Series_Name_TX= "Texas Field Production of Crude Oil, Monthly"
Series_ID_TX= "PET.MCRFPTX1.M"
#OS API
API_Call_GULF=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFP3FM1.M"
Series_Name_GULF= "Federal Offshore--Gulf of Mexico Field Production of Crude Oil, Monthly"
Series_ID_GULF= "PET.MCRFP3FM1.M"
#CO API
API_Call_CO=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPCO1.M"
Series_Name_CO= "Colorado Field Production of Crude Oil, Monthly"
Series_ID_CO= "PET.MCRFPCO1.M"
#ID API
API_Call_ID=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.M_EPC0_FPF_SID_MBBL.M"
Series_Name_ID= "Idaho Field Production of Crude Oil, Monthly"
Series_ID_ID= "PET.M_EPC0_FPF_SID_MBBL.M"
#MT API
API_Call_MT=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPMT1.M"
Series_Name_MT= "Montana Field Production of Crude Oil, Monthly"
Series_ID_MT= "PET.MCRFPMT1.M"
#UT API
API_Call_UT=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPUT1.M"
Series_Name_UT= "Utah Field Production of Crude Oil, Monthly"
Series_ID_UT= "PET.MCRFPUT1.M"
#WY API
API_Call_WY=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPWY1.M"
Series_Name_WY= "Wyoming Field Production of Crude Oil, Monthly"
Series_ID_WY= "PET.MCRFPWY1.M"
#AK API
API_Call_AK=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPAK1.M"
Series_Name_AK= "Alaska Field Production of Crude Oil, Monthly"
Series_ID_AK= "PET.MCRFPAK1.M"
#AZ API
API_Call_AZ=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPAZ1.M"
Series_Name_AZ= "Arizona Field Production of Crude Oil, Monthly"
Series_ID_AZ= "PET.MCRFPAZ1.M"
#CA API
API_Call_CA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPCA1.M"
Series_Name_CA= "California Field Production of Crude Oil, Monthly"
Series_ID_CA= "PET.MCRFPCA1.M"
#NV API
API_Call_NV=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFPNV1.M"
Series_Name_NV= "Nevada Field Production of Crude Oil, Monthly"
Series_ID_NV= "PET.MCRFPNV1.M"
#OS API
API_Call_OS_CA=f"http://api.eia.gov/series/?api_key={EIA_key}&series_id=PET.MCRFP5F1.M"
Series_Name_OS_CA= "Federal Offshore PADD 5 Field Production of Crude Oil, Monthly"
Series_ID_OS_CA= "PET.MCRFP5F1.M"

In [3]:
API_Calls=[API_Call_USA, API_Call_FL, API_Call_NY, API_Call_PA, API_Call_VA, API_Call_WV, API_Call_IL,API_Call_IN, API_Call_KS, API_Call_KY, API_Call_MI, API_Call_MO, API_Call_NE, API_Call_ND, API_Call_OH, API_Call_OK, API_Call_SD, API_Call_TN, API_Call_AL, API_Call_AR, API_Call_LA, API_Call_MS, API_Call_NM, API_Call_TX, API_Call_GULF, API_Call_CO, API_Call_ID, API_Call_MT, API_Call_UT, API_Call_WY, API_Call_AK, API_Call_AZ, API_Call_CA, API_Call_NV, API_Call_OS_CA]
Series_Names=[Series_Name_USA, Series_Name_FL, Series_Name_NY, Series_Name_PA, Series_Name_VA, Series_Name_WV, Series_Name_IL, Series_Name_IN, Series_Name_KS, Series_Name_KY, Series_Name_MI, Series_Name_MO, Series_Name_NE, Series_Name_ND, Series_Name_OH, Series_Name_OK, Series_Name_SD, Series_Name_TN, Series_Name_AL, Series_Name_AR, Series_Name_LA, Series_Name_MS, Series_Name_NM, Series_Name_TX, Series_Name_GULF, Series_Name_CO, Series_Name_ID, Series_Name_MT, Series_Name_UT, Series_Name_WY, Series_Name_AK, Series_Name_AZ, Series_Name_CA, Series_Name_NV, Series_Name_OS_CA]
Series_IDs=[Series_ID_USA, Series_ID_FL, Series_ID_NY, Series_ID_PA, Series_ID_VA, Series_ID_WV, Series_ID_IL, Series_ID_IN, Series_ID_KS, Series_ID_KY, Series_ID_MI, Series_ID_MO, Series_ID_NE, Series_ID_ND, Series_ID_OH, Series_ID_OK, Series_ID_SD, Series_ID_TN, Series_ID_AL, Series_ID_AR, Series_ID_LA, Series_ID_MS, Series_ID_NM, Series_ID_TX, Series_ID_GULF, Series_ID_CO, Series_ID_ID, Series_ID_MT, Series_ID_UT, Series_ID_WY, Series_ID_AK, Series_ID_AZ, Series_ID_CA, Series_ID_NV, Series_ID_OS_CA]

list_headers=[
"U.S. Field Production of Crude Oil, Monthly (Thousand Barrels)",
"Florida Field Production of Crude Oil, Monthly (Thousand Barrels)",
"New York Field Production of Crude Oil, Monthly (Thousand Barrels)",             
"Pennsylvania Field Production of Crude Oil, Monthly (Thousand Barrels)",
"Virginia Field Production of Crude Oil, Monthly (Thousand Barrels)",
"West Virginia Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Illinois Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Indiana Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Kansas Field Production of Crude Oil, Monthly (Thousand Barrels)",
"Kentucky Field Production of Crude Oil, Monthly (Thousand Barrels)",   
"Michigan Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Missouri Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Nebraska Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"North Dakota Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Ohio Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Oklahoma Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"South Dakota Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Tennessee Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Alabama Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Arkansas Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Louisiana Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Mississippi Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"New Mexico Field Production of Crude Oil, Monthly (Thousand Barrels)",      
"Texas Field Production of Crude Oil, Monthly (Thousand Barrels)",   
"Federal Offshore--Gulf of Mexico Field Production of Crude Oil, Monthly (Thousand Barrels)",   
"Colorado Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Idaho Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Montana Field Production of Crude Oil, Monthly (Thousand Barrels)",    
"Utah Field Production of Crude Oil, Monthly (Thousand Barrels)",     
"Wyoming Field Production of Crude Oil, Monthly (Thousand Barrels)",   
"Alaska Field Production of Crude Oil, Monthly (Thousand Barrels)", 
"Arizona Field Production of Crude Oil, Monthly (Thousand Barrels)", 
"California Field Production of Crude Oil, Monthly (Thousand Barrels)", 
"Nevada Field Production of Crude Oil, Monthly (Thousand Barrels)", 
"Federal Offshore PADD 5 Field Production of Crude Oil, Monthly (Thousand Barrels)",
]
numbers=(1,2,3,4,5,6,7,8, 9, 10,11, 12, 13, 14,15, 16, 17, 18, 19, 20, 21,22,23,24,25,26,27,28,28,30,31,32,33,34)
names=('USA_Prod','Florida, USA','New York, the US','Pennsylvania, USA','Virginia, USA','West Virginia, the US','Illinois, the US', 'Indiana, USA', 'Kansas, the US', 'Kentucky, USA', 'Michigan, USA', 'Missouri, USA', 'Nebraska, the US', 'North Dakota, USA', 'Ohio, USA', 'Oklahoma, the USA', 'South Dakota, the US', 'Tennessee, USA', 'Alabama, USA', 'Arkansas, the US', 'Louisiana, USA', 'Mississippi, the US', 'New Mexico, USA', 'Texas, the USA', 'GULF_Prod', 'Colorado, USA', 'Idaho, USA', 'Montana, USA', 'Utah, USA', 'Wyoming, USA', 'Alaska, USA', 'Arizona, USA', 'California, the USA', 'Nevada, USA', 'CAOffshore')

In [4]:
d={}
imports=[] 
bigdf = pd.DataFrame()

for i,j,k,m,n,name in zip(API_Calls, Series_Names, Series_IDs, list_headers, numbers, names):
    API_Call=i
    Series_Name= j
    Series_ID= k
    #install EIA package--- pip install EIA_python
    #pip install pyOpenSSL to get around SSL error
    #these are the API keys I set up
    api_key = EIA_key
    api = eia.API(api_key)
    #import data but still need to clean it
    series_search = api.data_by_series(series=Series_ID)
    df = pd.DataFrame(series_search)
    # define a series and pass through api and Series_ID
    def retrieve_time_series(api, Series_ID):
        """
        Return the time series dataframe, based on API and unique Series ID
        """
        #Retrieve Data By Series ID 
        series_search = api.data_by_series(series=Series_ID)
        ##Create a pandas dataframe from the retrieved time series
        global df
        df = pd.DataFrame(series_search)
        return df
    # define another function main to run the script through
    def main():
        """
        Run main script
        """
        #Create EIA API using your specific API key
        api_key = EIA_key
        api = eia.API(api_key)
        df=retrieve_time_series(api, Series_ID)
        #Print the returned dataframe df
        print(df)
    req = requests.get(i, verify = False)
    #Clean the dataframe by resetting the index because the date is automatically set as the index
    df.reset_index(inplace=True)
    #{original header: new name given}
    df.rename(columns={m:name}, inplace=True)
    #{index:Date}
    df.rename(columns={'index':'Date'}, inplace=True)
    #create a dataframe [[date, name of each state]]
    d=df[['Date', name]]
    #convert date to datetime[64]
    d['Date']=pd.to_datetime(d['Date'], errors='coerce')
    bigdf['Date']=d['Date']
    bigdf[name] = d[name]
bigdf=bigdf[0:476]

# Oil Production by State

In [5]:
bigdf[475:]

,Date,USA_Prod,"Florida, USA","New York, the US","Pennsylvania, USA","Virginia, USA","West Virginia, the US","Illinois, the US","Indiana, USA","Kansas, the US","Kentucky, USA","Michigan, USA","Missouri, USA","Nebraska, the US","North Dakota, USA","Ohio, USA","Oklahoma, the USA","South Dakota, the US","Tennessee, USA","Alabama, USA","Arkansas, the US","Louisiana, USA","Mississippi, the US","New Mexico, USA","Texas, the USA",GULF_Prod,"Colorado, USA","Idaho, USA","Montana, USA","Utah, USA","Wyoming, USA","Alaska, USA","Arizona, USA","California, the USA","Nevada, USA"
475,2020-08-01,209733,91.0,23.0,428.0,0.0,1615.0,619.0,122.0,2322.0,225.0,379.0,6.0,156.0,35812.0,2068.0,14250.0,85.0,14.0,309.0,326.0,2635.0,1239.0,31464.0,145289.0,37062.0,13779.0,NaN,1597.0,2783.0,7462.0,13751.0,1.0,11796.0,20.0

In [6]:
url='https://www.latlong.net/category/states-236-14.html'
df = pd.read_html(url)[0]
df.columns=['PlaceName','Latitude','Longitude']
df2=pd.DataFrame({"Production":[0,1615.0, 0, 145289.0, 85.0, 0, 0, 23.0, 0, 156.0, 2322.0, 1239.0, 619.0, 0, 0, 326.0, 122.0, 6.0, 91.0, 20.0, 0, 379.0, 0, 0, 13751.0, 14.0, 0, 0, 225.0, 35812.0, 0, 14250.0, 1597.0, 0, 2783.0, 13779.0, 2068.0, 309.0, 0, 31464.0, 0, 428.0, 1.0, 0.0, 0.0, 11796.0, 0.0, 7462.0, 0.0, 2635.0]})
df['Production']=df2['Production']
df_html=pd.concat([df, df2], axis=1)

In [7]:
df_html

                    PlaceName   Latitude   Longitude  Production  Production
0          Wisconsin, the USA  44.500000  -89.500000         0.0         0.0
1       West Virginia, the US  39.000000  -80.500000      1615.0      1615.0
2            Vermont, the USA  44.000000  -72.699997         0.0         0.0
3              Texas, the USA  31.000000 -100.000000    145289.0    145289.0
4        South Dakota, the US  44.500000 -100.000000        85.0        85.0
5        Rhode Island, the US  41.700001  -71.500000         0.0         0.0
6              Oregon, the US  44.000000 -120.500000         0.0         0.0
7            New York, the US  43.000000  -75.000000        23.0        23.0
8       New Hampshire, the US  44.000000  -71.500000         0.0         0.0
9            Nebraska, the US  41.500000 -100.000000       156.0       156.0
10             Kansas, the US  38.500000  -98.000000      2322.0      2322.0
11        Mississippi, the US  33.000000  -90.000000      1239.0      1239.0
12           Illinois, the US  40.000000  -89.000000       619.0       619.0
13           Delaware, the US  39.000000  -75.500000         0.0         0.0
14        Connecticut, the US  41.599998  -72.699997         0.0         0.0
15           Arkansas, the US  34.799999  -92.199997       326.0       326.0
16               Indiana, USA  40.273502  -86.126976       122.0       122.0
17              Missouri, USA  38.573936  -92.603760         6.0         6.0
18               Florida, USA  27.994402  -81.760254        91.0        91.0
19                Nevada, USA  39.876019 -117.224121        20.0        20.0
20             Maine, the USA  45.367584  -68.972168         0.0         0.0
21              Michigan, USA  44.182205  -84.506836       379.0       379.0
22           Georgia, the USA  33.247875  -83.441162         0.0         0.0
23                Hawaii, USA  19.741755 -155.844437         0.0         0.0
24                Alaska, USA  66.160507 -153.369141     13751.0     13751.0
25             Tennessee, USA  35.860119  -86.660156        14.0        14.0
26              Virginia, USA  37.926868  -78.024902         0.0         0.0
27            New Jersey, USA  39.833851  -74.871826         0.0         0.0
28              Kentucky, USA  37.839333  -84.270020       225.0       225.0
29          North Dakota, USA  47.650589 -100.437012     35812.0     35812.0
30             Minnesota, USA  46.392410  -94.636230         0.0         0.0
31          Oklahoma, the USA  36.084621  -96.921387     14250.0     14250.0
32               Montana, USA  46.965260 -109.533691      1597.0      1597.0
33  Washington State, the USA  47.751076 -120.740135         0.0         0.0
34                  Utah, USA  39.419220 -111.950684      2783.0      2783.0
35              Colorado, USA  39.113014 -105.358887     13779.0     13779.0
36                  Ohio, USA  40.367474  -82.996216      2068.0      2068.0
37               Alabama, USA  32.318230  -86.902298       309.0       309.0
38              Iowa, the USA  42.032974  -93.581543         0.0         0.0
39            New Mexico, USA  34.307144 -106.018066     31464.0     31464.0
40        South Carolina, USA  33.836082  -81.163727         0.0         0.0
41          Pennsylvania, USA  41.203323  -77.194527       428.0       428.0
42               Arizona, USA  34.048927 -111.093735         1.0         1.0
43              Maryland, USA  39.045753  -76.641273         0.0         0.0
44         Massachusetts, USA  42.407211  -71.382439         0.0         0.0
45        California, the USA  36.778259 -119.417931     11796.0     11796.0
46                 Idaho, USA  44.068203 -114.742043         0.0         0.0
47               Wyoming, USA  43.075970 -107.290283      7462.0      7462.0
48        North Carolina, USA  35.782169  -80.793457         0.0         0.0
49             Louisiana, USA  30.391830  -92.329102      2635.0      2635.0

In [8]:
result=df_html.to_json(orient='table')
parsed=json.loads(result)
print(json.dumps(parsed, indent=4))

{
    "schema": {
        "fields": [
            {
                "name": "index",
                "type": "integer"
            },
            {
                "name": "PlaceName",
                "type": "string"
            },
            {
                "name": "Latitude",
                "type": "number"
            },
            {
                "name": "Longitude",
                "type": "number"
            },
            {
                "name": "Production",
                "type": "number"
            },
            {
                "name": "Production",
                "type": "number"
            }
        ],
        "primaryKey": [
            "index"
        ],
        "pandas_version": "0.20.0"
    },
    "data": [
        {
            "index": 0,
            "PlaceName": "Wisconsin, the USA",
            "Latitude": 44.5,
            "Longitude": -89.5,
            "Production": 0.0
        },
        {
            "index": 1,
            "PlaceName": "West Virginia, the US",
            "Latitude": 39.0,
            "Longitude": -80.5,
            "Production": 1615.0
        },
        {
            "index": 2,
            "PlaceName": "Vermont, the USA",
            "Latitude": 44.0,
            "Longitude": -72.699997,
            "Production": 0.0
        },
        {
            "index": 3,
            "PlaceName": "Texas, the USA",
            "Latitude": 31.0,
            "Longitude": -100.0,
            "Production": 145289.0
        },
        {
            "index": 4,
            "PlaceName": "South Dakota, the US",
            "Latitude": 44.5,
            "Longitude": -100.0,
            "Production": 85.0
        },
        {
            "index": 5,
            "PlaceName": "Rhode Island, the US",
            "Latitude": 41.700001,
            "Longitude": -71.5,
            "Production": 0.0
        },
        {
            "index": 6,
            "PlaceName": "Oregon, the US",
            "Latitude": 44.0,
            "Longitude": -120.5,
            "Production": 0.0
        },
        {
            "index": 7,
            "PlaceName": "New York, the US",
            "Latitude": 43.0,
            "Longitude": -75.0,
            "Production": 23.0
        },
        {
            "index": 8,
            "PlaceName": "New Hampshire, the US",
            "Latitude": 44.0,
            "Longitude": -71.5,
            "Production": 0.0
        },
        {
            "index": 9,
            "PlaceName": "Nebraska, the US",
            "Latitude": 41.5,
            "Longitude": -100.0,
            "Production": 156.0
        },
        {
            "index": 10,
            "PlaceName": "Kansas, the US",
            "Latitude": 38.5,
            "Longitude": -98.0,
            "Production": 2322.0
        },
        {
            "index": 11,
            "PlaceName": "Mississippi, the US",
            "Latitude": 33.0,
            "Longitude": -90.0,
            "Production": 1239.0
        },
        {
            "index": 12,
            "PlaceName": "Illinois, the US",
            "Latitude": 40.0,
            "Longitude": -89.0,
            "Production": 619.0
        },
        {
            "index": 13,
            "PlaceName": "Delaware, the US",
            "Latitude": 39.0,
            "Longitude": -75.5,
            "Production": 0.0
        },
        {
            "index": 14,
            "PlaceName": "Connecticut, the US",
            "Latitude": 41.599998,
            "Longitude": -72.699997,
            "Production": 0.0
        },
        {
            "index": 15,
            "PlaceName": "Arkansas, the US",
            "Latitude": 34.799999,
            "Longitude": -92.199997,
            "Production": 326.0
        },
        {
            "index": 16,
            "PlaceName": "Indiana, USA",
            "Latitude": 40.273502,
            "Longitude": -86.126976,
            "Production": 122.0
        },
        {
            "index": 17,
            "PlaceName": "Missouri, USA",
            "Latitude": 38.573936,
            "Longitude": -92.60376,
            "Production": 6.0
        },
        {
            "index": 18,
            "PlaceName": "Florida, USA",
            "Latitude": 27.994402,
            "Longitude": -81.760254,
            "Production": 91.0
        },
        {
            "index": 19,
            "PlaceName": "Nevada, USA",
            "Latitude": 39.876019,
            "Longitude": -117.224121,
            "Production": 20.0
        },
        {
            "index": 20,
            "PlaceName": "Maine, the USA",
            "Latitude": 45.367584,
            "Longitude": -68.972168,
            "Production": 0.0
        },
        {
            "index": 21,
            "PlaceName": "Michigan, USA",
            "Latitude": 44.182205,
            "Longitude": -84.506836,
            "Production": 379.0
        },
        {
            "index": 22,
            "PlaceName": "Georgia, the USA",
            "Latitude": 33.247875,
            "Longitude": -83.441162,
            "Production": 0.0
        },
        {
            "index": 23,
            "PlaceName": "Hawaii, USA",
            "Latitude": 19.741755,
            "Longitude": -155.844437,
            "Production": 0.0
        },
        {
            "index": 24,
            "PlaceName": "Alaska, USA",
            "Latitude": 66.160507,
            "Longitude": -153.369141,
            "Production": 13751.0
        },
        {
            "index": 25,
            "PlaceName": "Tennessee, USA",
            "Latitude": 35.860119,
            "Longitude": -86.660156,
            "Production": 14.0
        },
        {
            "index": 26,
            "PlaceName": "Virginia, USA",
            "Latitude": 37.926868,
            "Longitude": -78.024902,
            "Production": 0.0
        },
        {
            "index": 27,
            "PlaceName": "New Jersey, USA",
            "Latitude": 39.833851,
            "Longitude": -74.871826,
            "Production": 0.0
        },
        {
            "index": 28,
            "PlaceName": "Kentucky, USA",
            "Latitude": 37.839333,
            "Longitude": -84.27002,
            "Production": 225.0
        },
        {
            "index": 29,
            "PlaceName": "North Dakota, USA",
            "Latitude": 47.650589,
            "Longitude": -100.437012,
            "Production": 35812.0
        },
        {
            "index": 30,
            "PlaceName": "Minnesota, USA",
            "Latitude": 46.39241,
            "Longitude": -94.63623,
            "Production": 0.0
        },
        {
            "index": 31,
            "PlaceName": "Oklahoma, the USA",
            "Latitude": 36.084621,
            "Longitude": -96.921387,
            "Production": 14250.0
        },
        {
            "index": 32,
            "PlaceName": "Montana, USA",
            "Latitude": 46.96526,
            "Longitude": -109.533691,
            "Production": 1597.0
        },
        {
            "index": 33,
            "PlaceName": "Washington State, the USA",
            "Latitude": 47.751076,
            "Longitude": -120.740135,
            "Production": 0.0
        },
        {
            "index": 34,
            "PlaceName": "Utah, USA",
            "Latitude": 39.41922,
            "Longitude": -111.950684,
            "Production": 2783.0
        },
        {
            "index": 35,
            "PlaceName": "Colorado, USA",
            "Latitude": 39.113014,
            "Longitude": -105.358887,
            "Production": 13779.0
        },
        {
            "index": 36,
            "PlaceName": "Ohio, USA",
            "Latitude": 40.367474,
            "Longitude": -82.996216,
            "Production": 2068.0
        },
        {
            "index": 37,
            "PlaceName": "Alabama, USA",
            "Latitude": 32.31823,
            "Longitude": -86.902298,
            "Production": 309.0
        },
        {
            "index": 38,
            "PlaceName": "Iowa, the USA",
            "Latitude": 42.032974,
            "Longitude": -93.581543,
            "Production": 0.0
        },
        {
            "index": 39,
            "PlaceName": "New Mexico, USA",
            "Latitude": 34.307144,
            "Longitude": -106.018066,
            "Production": 31464.0
        },
        {
            "index": 40,
            "PlaceName": "South Carolina, USA",
            "Latitude": 33.836082,
            "Longitude": -81.163727,
            "Production": 0.0
        },
        {
            "index": 41,
            "PlaceName": "Pennsylvania, USA",
            "Latitude": 41.203323,
            "Longitude": -77.194527,
            "Production": 428.0
        },
        {
            "index": 42,
            "PlaceName": "Arizona, USA",
            "Latitude": 34.048927,
            "Longitude": -111.093735,
            "Production": 1.0
        },
        {
            "index": 43,
            "PlaceName": "Maryland, USA",
            "Latitude": 39.045753,
            "Longitude": -76.641273,
            "Production": 0.0
        },
        {
            "index": 44,
            "PlaceName": "Massachusetts, USA",
            "Latitude": 42.407211,
            "Longitude": -71.382439,
            "Production": 0.0
        },
        {
            "index": 45,
            "PlaceName": "California, the USA",
            "Latitude": 36.778259,
            "Longitude": -119.417931,
            "Production": 11796.0
        },
        {
            "index": 46,
            "PlaceName": "Idaho, USA",
            "Latitude": 44.068203,
            "Longitude": -114.742043,
            "Production": 0.0
        },
        {
            "index": 47,
            "PlaceName": "Wyoming, USA",
            "Latitude": 43.07597,
            "Longitude": -107.290283,
            "Production": 7462.0
        },
        {
            "index": 48,
            "PlaceName": "North Carolina, USA",
            "Latitude": 35.782169,
            "Longitude": -80.793457,
            "Production": 0.0
        },
        {
            "index": 49,
            "PlaceName": "Louisiana, USA",
            "Latitude": 30.39183,
            "Longitude": -92.329102,
            "Production": 2635.0
        }
    ]
}